/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetUserVirtualCardResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUserVirtualCardResponse{}

// GetUserVirtualCardResponse struct for GetUserVirtualCardResponse
type GetUserVirtualCardResponse struct {
	Points          int32                          `json:"points"`
	OwnedItems      []OwnedItemAPIModel            `json:"ownedItems,omitempty"`
	BusinessDetails *PublicBusinessDetailsAPIModel `json:"businessDetails,omitempty"`
}

// NewGetUserVirtualCardResponse instantiates a new GetUserVirtualCardResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserVirtualCardResponse(points int32) *GetUserVirtualCardResponse {
	this := GetUserVirtualCardResponse{}
	this.Points = points
	return &this
}

// NewGetUserVirtualCardResponseWithDefaults instantiates a new GetUserVirtualCardResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserVirtualCardResponseWithDefaults() *GetUserVirtualCardResponse {
	this := GetUserVirtualCardResponse{}
	return &this
}

// GetPoints returns the Points field value
func (o *GetUserVirtualCardResponse) GetPoints() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *GetUserVirtualCardResponse) GetPointsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Points, true
}

// SetPoints sets field value
func (o *GetUserVirtualCardResponse) SetPoints(v int32) {
	o.Points = v
}

// GetOwnedItems returns the OwnedItems field value if set, zero value otherwise.
func (o *GetUserVirtualCardResponse) GetOwnedItems() []OwnedItemAPIModel {
	if o == nil || isNil(o.OwnedItems) {
		var ret []OwnedItemAPIModel
		return ret
	}
	return o.OwnedItems
}

// GetOwnedItemsOk returns a tuple with the OwnedItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserVirtualCardResponse) GetOwnedItemsOk() ([]OwnedItemAPIModel, bool) {
	if o == nil || isNil(o.OwnedItems) {
		return nil, false
	}
	return o.OwnedItems, true
}

// HasOwnedItems returns a boolean if a field has been set.
func (o *GetUserVirtualCardResponse) HasOwnedItems() bool {
	if o != nil && !isNil(o.OwnedItems) {
		return true
	}

	return false
}

// SetOwnedItems gets a reference to the given []OwnedItemAPIModel and assigns it to the OwnedItems field.
func (o *GetUserVirtualCardResponse) SetOwnedItems(v []OwnedItemAPIModel) {
	o.OwnedItems = v
}

// GetBusinessDetails returns the BusinessDetails field value if set, zero value otherwise.
func (o *GetUserVirtualCardResponse) GetBusinessDetails() PublicBusinessDetailsAPIModel {
	if o == nil || isNil(o.BusinessDetails) {
		var ret PublicBusinessDetailsAPIModel
		return ret
	}
	return *o.BusinessDetails
}

// GetBusinessDetailsOk returns a tuple with the BusinessDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserVirtualCardResponse) GetBusinessDetailsOk() (*PublicBusinessDetailsAPIModel, bool) {
	if o == nil || isNil(o.BusinessDetails) {
		return nil, false
	}
	return o.BusinessDetails, true
}

// HasBusinessDetails returns a boolean if a field has been set.
func (o *GetUserVirtualCardResponse) HasBusinessDetails() bool {
	if o != nil && !isNil(o.BusinessDetails) {
		return true
	}

	return false
}

// SetBusinessDetails gets a reference to the given PublicBusinessDetailsAPIModel and assigns it to the BusinessDetails field.
func (o *GetUserVirtualCardResponse) SetBusinessDetails(v PublicBusinessDetailsAPIModel) {
	o.BusinessDetails = &v
}

func (o GetUserVirtualCardResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUserVirtualCardResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["points"] = o.Points
	if !isNil(o.OwnedItems) {
		toSerialize["ownedItems"] = o.OwnedItems
	}
	if !isNil(o.BusinessDetails) {
		toSerialize["businessDetails"] = o.BusinessDetails
	}
	return toSerialize, nil
}

type NullableGetUserVirtualCardResponse struct {
	value *GetUserVirtualCardResponse
	isSet bool
}

func (v NullableGetUserVirtualCardResponse) Get() *GetUserVirtualCardResponse {
	return v.value
}

func (v *NullableGetUserVirtualCardResponse) Set(val *GetUserVirtualCardResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserVirtualCardResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserVirtualCardResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserVirtualCardResponse(val *GetUserVirtualCardResponse) *NullableGetUserVirtualCardResponse {
	return &NullableGetUserVirtualCardResponse{value: val, isSet: true}
}

func (v NullableGetUserVirtualCardResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserVirtualCardResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
