/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostAccountSessionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostAccountSessionResponse{}

// PostAccountSessionResponse struct for PostAccountSessionResponse
type PostAccountSessionResponse struct {
	Token *string `json:"token,omitempty"`
}

// NewPostAccountSessionResponse instantiates a new PostAccountSessionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostAccountSessionResponse() *PostAccountSessionResponse {
	this := PostAccountSessionResponse{}
	return &this
}

// NewPostAccountSessionResponseWithDefaults instantiates a new PostAccountSessionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostAccountSessionResponseWithDefaults() *PostAccountSessionResponse {
	this := PostAccountSessionResponse{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *PostAccountSessionResponse) GetToken() string {
	if o == nil || isNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostAccountSessionResponse) GetTokenOk() (*string, bool) {
	if o == nil || isNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *PostAccountSessionResponse) HasToken() bool {
	if o != nil && !isNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *PostAccountSessionResponse) SetToken(v string) {
	o.Token = &v
}

func (o PostAccountSessionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostAccountSessionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullablePostAccountSessionResponse struct {
	value *PostAccountSessionResponse
	isSet bool
}

func (v NullablePostAccountSessionResponse) Get() *PostAccountSessionResponse {
	return v.value
}

func (v *NullablePostAccountSessionResponse) Set(val *PostAccountSessionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePostAccountSessionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePostAccountSessionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostAccountSessionResponse(val *PostAccountSessionResponse) *NullablePostAccountSessionResponse {
	return &NullablePostAccountSessionResponse{value: val, isSet: true}
}

func (v NullablePostAccountSessionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostAccountSessionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
