/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetBusinessTransactionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBusinessTransactionResponse{}

// GetBusinessTransactionResponse struct for GetBusinessTransactionResponse
type GetBusinessTransactionResponse struct {
	PublicId      *string                         `json:"publicId,omitempty"`
	VirtualCardId *int32                          `json:"virtualCardId,omitempty"`
	State         *TransactionStateEnum           `json:"state,omitempty"`
	Items         []TransactionItemDetailAPIModel `json:"items,omitempty"`
}

// NewGetBusinessTransactionResponse instantiates a new GetBusinessTransactionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBusinessTransactionResponse() *GetBusinessTransactionResponse {
	this := GetBusinessTransactionResponse{}
	return &this
}

// NewGetBusinessTransactionResponseWithDefaults instantiates a new GetBusinessTransactionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBusinessTransactionResponseWithDefaults() *GetBusinessTransactionResponse {
	this := GetBusinessTransactionResponse{}
	return &this
}

// GetPublicId returns the PublicId field value if set, zero value otherwise.
func (o *GetBusinessTransactionResponse) GetPublicId() string {
	if o == nil || isNil(o.PublicId) {
		var ret string
		return ret
	}
	return *o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessTransactionResponse) GetPublicIdOk() (*string, bool) {
	if o == nil || isNil(o.PublicId) {
		return nil, false
	}
	return o.PublicId, true
}

// HasPublicId returns a boolean if a field has been set.
func (o *GetBusinessTransactionResponse) HasPublicId() bool {
	if o != nil && !isNil(o.PublicId) {
		return true
	}

	return false
}

// SetPublicId gets a reference to the given string and assigns it to the PublicId field.
func (o *GetBusinessTransactionResponse) SetPublicId(v string) {
	o.PublicId = &v
}

// GetVirtualCardId returns the VirtualCardId field value if set, zero value otherwise.
func (o *GetBusinessTransactionResponse) GetVirtualCardId() int32 {
	if o == nil || isNil(o.VirtualCardId) {
		var ret int32
		return ret
	}
	return *o.VirtualCardId
}

// GetVirtualCardIdOk returns a tuple with the VirtualCardId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessTransactionResponse) GetVirtualCardIdOk() (*int32, bool) {
	if o == nil || isNil(o.VirtualCardId) {
		return nil, false
	}
	return o.VirtualCardId, true
}

// HasVirtualCardId returns a boolean if a field has been set.
func (o *GetBusinessTransactionResponse) HasVirtualCardId() bool {
	if o != nil && !isNil(o.VirtualCardId) {
		return true
	}

	return false
}

// SetVirtualCardId gets a reference to the given int32 and assigns it to the VirtualCardId field.
func (o *GetBusinessTransactionResponse) SetVirtualCardId(v int32) {
	o.VirtualCardId = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *GetBusinessTransactionResponse) GetState() TransactionStateEnum {
	if o == nil || isNil(o.State) {
		var ret TransactionStateEnum
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessTransactionResponse) GetStateOk() (*TransactionStateEnum, bool) {
	if o == nil || isNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *GetBusinessTransactionResponse) HasState() bool {
	if o != nil && !isNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given TransactionStateEnum and assigns it to the State field.
func (o *GetBusinessTransactionResponse) SetState(v TransactionStateEnum) {
	o.State = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *GetBusinessTransactionResponse) GetItems() []TransactionItemDetailAPIModel {
	if o == nil || isNil(o.Items) {
		var ret []TransactionItemDetailAPIModel
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessTransactionResponse) GetItemsOk() ([]TransactionItemDetailAPIModel, bool) {
	if o == nil || isNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *GetBusinessTransactionResponse) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []TransactionItemDetailAPIModel and assigns it to the Items field.
func (o *GetBusinessTransactionResponse) SetItems(v []TransactionItemDetailAPIModel) {
	o.Items = v
}

func (o GetBusinessTransactionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBusinessTransactionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PublicId) {
		toSerialize["publicId"] = o.PublicId
	}
	if !isNil(o.VirtualCardId) {
		toSerialize["virtualCardId"] = o.VirtualCardId
	}
	if !isNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableGetBusinessTransactionResponse struct {
	value *GetBusinessTransactionResponse
	isSet bool
}

func (v NullableGetBusinessTransactionResponse) Get() *GetBusinessTransactionResponse {
	return v.value
}

func (v *NullableGetBusinessTransactionResponse) Set(val *GetBusinessTransactionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBusinessTransactionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBusinessTransactionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBusinessTransactionResponse(val *GetBusinessTransactionResponse) *NullableGetBusinessTransactionResponse {
	return &NullableGetBusinessTransactionResponse{value: val, isSet: true}
}

func (v NullableGetBusinessTransactionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBusinessTransactionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
