/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostBusinessItemDefinitionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostBusinessItemDefinitionResponse{}

// PostBusinessItemDefinitionResponse struct for PostBusinessItemDefinitionResponse
type PostBusinessItemDefinitionResponse struct {
	PublicId *string `json:"publicId,omitempty"`
}

// NewPostBusinessItemDefinitionResponse instantiates a new PostBusinessItemDefinitionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostBusinessItemDefinitionResponse() *PostBusinessItemDefinitionResponse {
	this := PostBusinessItemDefinitionResponse{}
	return &this
}

// NewPostBusinessItemDefinitionResponseWithDefaults instantiates a new PostBusinessItemDefinitionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostBusinessItemDefinitionResponseWithDefaults() *PostBusinessItemDefinitionResponse {
	this := PostBusinessItemDefinitionResponse{}
	return &this
}

// GetPublicId returns the PublicId field value if set, zero value otherwise.
func (o *PostBusinessItemDefinitionResponse) GetPublicId() string {
	if o == nil || isNil(o.PublicId) {
		var ret string
		return ret
	}
	return *o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessItemDefinitionResponse) GetPublicIdOk() (*string, bool) {
	if o == nil || isNil(o.PublicId) {
		return nil, false
	}
	return o.PublicId, true
}

// HasPublicId returns a boolean if a field has been set.
func (o *PostBusinessItemDefinitionResponse) HasPublicId() bool {
	if o != nil && !isNil(o.PublicId) {
		return true
	}

	return false
}

// SetPublicId gets a reference to the given string and assigns it to the PublicId field.
func (o *PostBusinessItemDefinitionResponse) SetPublicId(v string) {
	o.PublicId = &v
}

func (o PostBusinessItemDefinitionResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostBusinessItemDefinitionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PublicId) {
		toSerialize["publicId"] = o.PublicId
	}
	return toSerialize, nil
}

type NullablePostBusinessItemDefinitionResponse struct {
	value *PostBusinessItemDefinitionResponse
	isSet bool
}

func (v NullablePostBusinessItemDefinitionResponse) Get() *PostBusinessItemDefinitionResponse {
	return v.value
}

func (v *NullablePostBusinessItemDefinitionResponse) Set(val *PostBusinessItemDefinitionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePostBusinessItemDefinitionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePostBusinessItemDefinitionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostBusinessItemDefinitionResponse(val *PostBusinessItemDefinitionResponse) *NullablePostBusinessItemDefinitionResponse {
	return &NullablePostBusinessItemDefinitionResponse{value: val, isSet: true}
}

func (v NullablePostBusinessItemDefinitionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostBusinessItemDefinitionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
