/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OwnedItemAPIModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OwnedItemAPIModel{}

// OwnedItemAPIModel struct for OwnedItemAPIModel
type OwnedItemAPIModel struct {
	PublicId     *string `json:"publicId,omitempty"`
	DefinitionId *string `json:"definitionId,omitempty"`
}

// NewOwnedItemAPIModel instantiates a new OwnedItemAPIModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOwnedItemAPIModel() *OwnedItemAPIModel {
	this := OwnedItemAPIModel{}
	return &this
}

// NewOwnedItemAPIModelWithDefaults instantiates a new OwnedItemAPIModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOwnedItemAPIModelWithDefaults() *OwnedItemAPIModel {
	this := OwnedItemAPIModel{}
	return &this
}

// GetPublicId returns the PublicId field value if set, zero value otherwise.
func (o *OwnedItemAPIModel) GetPublicId() string {
	if o == nil || isNil(o.PublicId) {
		var ret string
		return ret
	}
	return *o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnedItemAPIModel) GetPublicIdOk() (*string, bool) {
	if o == nil || isNil(o.PublicId) {
		return nil, false
	}
	return o.PublicId, true
}

// HasPublicId returns a boolean if a field has been set.
func (o *OwnedItemAPIModel) HasPublicId() bool {
	if o != nil && !isNil(o.PublicId) {
		return true
	}

	return false
}

// SetPublicId gets a reference to the given string and assigns it to the PublicId field.
func (o *OwnedItemAPIModel) SetPublicId(v string) {
	o.PublicId = &v
}

// GetDefinitionId returns the DefinitionId field value if set, zero value otherwise.
func (o *OwnedItemAPIModel) GetDefinitionId() string {
	if o == nil || isNil(o.DefinitionId) {
		var ret string
		return ret
	}
	return *o.DefinitionId
}

// GetDefinitionIdOk returns a tuple with the DefinitionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OwnedItemAPIModel) GetDefinitionIdOk() (*string, bool) {
	if o == nil || isNil(o.DefinitionId) {
		return nil, false
	}
	return o.DefinitionId, true
}

// HasDefinitionId returns a boolean if a field has been set.
func (o *OwnedItemAPIModel) HasDefinitionId() bool {
	if o != nil && !isNil(o.DefinitionId) {
		return true
	}

	return false
}

// SetDefinitionId gets a reference to the given string and assigns it to the DefinitionId field.
func (o *OwnedItemAPIModel) SetDefinitionId(v string) {
	o.DefinitionId = &v
}

func (o OwnedItemAPIModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OwnedItemAPIModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PublicId) {
		toSerialize["publicId"] = o.PublicId
	}
	if !isNil(o.DefinitionId) {
		toSerialize["definitionId"] = o.DefinitionId
	}
	return toSerialize, nil
}

type NullableOwnedItemAPIModel struct {
	value *OwnedItemAPIModel
	isSet bool
}

func (v NullableOwnedItemAPIModel) Get() *OwnedItemAPIModel {
	return v.value
}

func (v *NullableOwnedItemAPIModel) Set(val *OwnedItemAPIModel) {
	v.value = val
	v.isSet = true
}

func (v NullableOwnedItemAPIModel) IsSet() bool {
	return v.isSet
}

func (v *NullableOwnedItemAPIModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOwnedItemAPIModel(val *OwnedItemAPIModel) *NullableOwnedItemAPIModel {
	return &NullableOwnedItemAPIModel{value: val, isSet: true}
}

func (v NullableOwnedItemAPIModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOwnedItemAPIModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
