/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetBusinessAccountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBusinessAccountResponse{}

// GetBusinessAccountResponse struct for GetBusinessAccountResponse
type GetBusinessAccountResponse struct {
	PublicId        *string                  `json:"publicId,omitempty"`
	Name            *string                  `json:"name,omitempty"`
	Address         *string                  `json:"address,omitempty"`
	GpsCoordinates  *string                  `json:"gpsCoordinates,omitempty"`
	BannerImageId   *string                  `json:"bannerImageId,omitempty"`
	Description     *string                  `json:"description,omitempty"`
	IconImageId     *string                  `json:"iconImageId,omitempty"`
	MenuImageIds    []string                 `json:"menuImageIds,omitempty"`
	ItemDefinitions []ItemDefinitionAPIModel `json:"itemDefinitions,omitempty"`
	Nip             *string                  `json:"nip,omitempty"`
	Krs             *string                  `json:"krs,omitempty"`
	Regon           *string                  `json:"regon,omitempty"`
	OwnerName       *string                  `json:"ownerName,omitempty"`
}

// NewGetBusinessAccountResponse instantiates a new GetBusinessAccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBusinessAccountResponse() *GetBusinessAccountResponse {
	this := GetBusinessAccountResponse{}
	return &this
}

// NewGetBusinessAccountResponseWithDefaults instantiates a new GetBusinessAccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBusinessAccountResponseWithDefaults() *GetBusinessAccountResponse {
	this := GetBusinessAccountResponse{}
	return &this
}

// GetPublicId returns the PublicId field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetPublicId() string {
	if o == nil || isNil(o.PublicId) {
		var ret string
		return ret
	}
	return *o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetPublicIdOk() (*string, bool) {
	if o == nil || isNil(o.PublicId) {
		return nil, false
	}
	return o.PublicId, true
}

// HasPublicId returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasPublicId() bool {
	if o != nil && !isNil(o.PublicId) {
		return true
	}

	return false
}

// SetPublicId gets a reference to the given string and assigns it to the PublicId field.
func (o *GetBusinessAccountResponse) SetPublicId(v string) {
	o.PublicId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetBusinessAccountResponse) SetName(v string) {
	o.Name = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetAddress() string {
	if o == nil || isNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetAddressOk() (*string, bool) {
	if o == nil || isNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasAddress() bool {
	if o != nil && !isNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *GetBusinessAccountResponse) SetAddress(v string) {
	o.Address = &v
}

// GetGpsCoordinates returns the GpsCoordinates field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetGpsCoordinates() string {
	if o == nil || isNil(o.GpsCoordinates) {
		var ret string
		return ret
	}
	return *o.GpsCoordinates
}

// GetGpsCoordinatesOk returns a tuple with the GpsCoordinates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetGpsCoordinatesOk() (*string, bool) {
	if o == nil || isNil(o.GpsCoordinates) {
		return nil, false
	}
	return o.GpsCoordinates, true
}

// HasGpsCoordinates returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasGpsCoordinates() bool {
	if o != nil && !isNil(o.GpsCoordinates) {
		return true
	}

	return false
}

// SetGpsCoordinates gets a reference to the given string and assigns it to the GpsCoordinates field.
func (o *GetBusinessAccountResponse) SetGpsCoordinates(v string) {
	o.GpsCoordinates = &v
}

// GetBannerImageId returns the BannerImageId field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetBannerImageId() string {
	if o == nil || isNil(o.BannerImageId) {
		var ret string
		return ret
	}
	return *o.BannerImageId
}

// GetBannerImageIdOk returns a tuple with the BannerImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetBannerImageIdOk() (*string, bool) {
	if o == nil || isNil(o.BannerImageId) {
		return nil, false
	}
	return o.BannerImageId, true
}

// HasBannerImageId returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasBannerImageId() bool {
	if o != nil && !isNil(o.BannerImageId) {
		return true
	}

	return false
}

// SetBannerImageId gets a reference to the given string and assigns it to the BannerImageId field.
func (o *GetBusinessAccountResponse) SetBannerImageId(v string) {
	o.BannerImageId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetBusinessAccountResponse) SetDescription(v string) {
	o.Description = &v
}

// GetIconImageId returns the IconImageId field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetIconImageId() string {
	if o == nil || isNil(o.IconImageId) {
		var ret string
		return ret
	}
	return *o.IconImageId
}

// GetIconImageIdOk returns a tuple with the IconImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetIconImageIdOk() (*string, bool) {
	if o == nil || isNil(o.IconImageId) {
		return nil, false
	}
	return o.IconImageId, true
}

// HasIconImageId returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasIconImageId() bool {
	if o != nil && !isNil(o.IconImageId) {
		return true
	}

	return false
}

// SetIconImageId gets a reference to the given string and assigns it to the IconImageId field.
func (o *GetBusinessAccountResponse) SetIconImageId(v string) {
	o.IconImageId = &v
}

// GetMenuImageIds returns the MenuImageIds field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetMenuImageIds() []string {
	if o == nil || isNil(o.MenuImageIds) {
		var ret []string
		return ret
	}
	return o.MenuImageIds
}

// GetMenuImageIdsOk returns a tuple with the MenuImageIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetMenuImageIdsOk() ([]string, bool) {
	if o == nil || isNil(o.MenuImageIds) {
		return nil, false
	}
	return o.MenuImageIds, true
}

// HasMenuImageIds returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasMenuImageIds() bool {
	if o != nil && !isNil(o.MenuImageIds) {
		return true
	}

	return false
}

// SetMenuImageIds gets a reference to the given []string and assigns it to the MenuImageIds field.
func (o *GetBusinessAccountResponse) SetMenuImageIds(v []string) {
	o.MenuImageIds = v
}

// GetItemDefinitions returns the ItemDefinitions field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetItemDefinitions() []ItemDefinitionAPIModel {
	if o == nil || isNil(o.ItemDefinitions) {
		var ret []ItemDefinitionAPIModel
		return ret
	}
	return o.ItemDefinitions
}

// GetItemDefinitionsOk returns a tuple with the ItemDefinitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetItemDefinitionsOk() ([]ItemDefinitionAPIModel, bool) {
	if o == nil || isNil(o.ItemDefinitions) {
		return nil, false
	}
	return o.ItemDefinitions, true
}

// HasItemDefinitions returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasItemDefinitions() bool {
	if o != nil && !isNil(o.ItemDefinitions) {
		return true
	}

	return false
}

// SetItemDefinitions gets a reference to the given []ItemDefinitionAPIModel and assigns it to the ItemDefinitions field.
func (o *GetBusinessAccountResponse) SetItemDefinitions(v []ItemDefinitionAPIModel) {
	o.ItemDefinitions = v
}

// GetNip returns the Nip field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetNip() string {
	if o == nil || isNil(o.Nip) {
		var ret string
		return ret
	}
	return *o.Nip
}

// GetNipOk returns a tuple with the Nip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetNipOk() (*string, bool) {
	if o == nil || isNil(o.Nip) {
		return nil, false
	}
	return o.Nip, true
}

// HasNip returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasNip() bool {
	if o != nil && !isNil(o.Nip) {
		return true
	}

	return false
}

// SetNip gets a reference to the given string and assigns it to the Nip field.
func (o *GetBusinessAccountResponse) SetNip(v string) {
	o.Nip = &v
}

// GetKrs returns the Krs field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetKrs() string {
	if o == nil || isNil(o.Krs) {
		var ret string
		return ret
	}
	return *o.Krs
}

// GetKrsOk returns a tuple with the Krs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetKrsOk() (*string, bool) {
	if o == nil || isNil(o.Krs) {
		return nil, false
	}
	return o.Krs, true
}

// HasKrs returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasKrs() bool {
	if o != nil && !isNil(o.Krs) {
		return true
	}

	return false
}

// SetKrs gets a reference to the given string and assigns it to the Krs field.
func (o *GetBusinessAccountResponse) SetKrs(v string) {
	o.Krs = &v
}

// GetRegon returns the Regon field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetRegon() string {
	if o == nil || isNil(o.Regon) {
		var ret string
		return ret
	}
	return *o.Regon
}

// GetRegonOk returns a tuple with the Regon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetRegonOk() (*string, bool) {
	if o == nil || isNil(o.Regon) {
		return nil, false
	}
	return o.Regon, true
}

// HasRegon returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasRegon() bool {
	if o != nil && !isNil(o.Regon) {
		return true
	}

	return false
}

// SetRegon gets a reference to the given string and assigns it to the Regon field.
func (o *GetBusinessAccountResponse) SetRegon(v string) {
	o.Regon = &v
}

// GetOwnerName returns the OwnerName field value if set, zero value otherwise.
func (o *GetBusinessAccountResponse) GetOwnerName() string {
	if o == nil || isNil(o.OwnerName) {
		var ret string
		return ret
	}
	return *o.OwnerName
}

// GetOwnerNameOk returns a tuple with the OwnerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponse) GetOwnerNameOk() (*string, bool) {
	if o == nil || isNil(o.OwnerName) {
		return nil, false
	}
	return o.OwnerName, true
}

// HasOwnerName returns a boolean if a field has been set.
func (o *GetBusinessAccountResponse) HasOwnerName() bool {
	if o != nil && !isNil(o.OwnerName) {
		return true
	}

	return false
}

// SetOwnerName gets a reference to the given string and assigns it to the OwnerName field.
func (o *GetBusinessAccountResponse) SetOwnerName(v string) {
	o.OwnerName = &v
}

func (o GetBusinessAccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBusinessAccountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PublicId) {
		toSerialize["publicId"] = o.PublicId
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !isNil(o.GpsCoordinates) {
		toSerialize["gpsCoordinates"] = o.GpsCoordinates
	}
	if !isNil(o.BannerImageId) {
		toSerialize["bannerImageId"] = o.BannerImageId
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.IconImageId) {
		toSerialize["iconImageId"] = o.IconImageId
	}
	if !isNil(o.MenuImageIds) {
		toSerialize["menuImageIds"] = o.MenuImageIds
	}
	if !isNil(o.ItemDefinitions) {
		toSerialize["itemDefinitions"] = o.ItemDefinitions
	}
	if !isNil(o.Nip) {
		toSerialize["nip"] = o.Nip
	}
	if !isNil(o.Krs) {
		toSerialize["krs"] = o.Krs
	}
	if !isNil(o.Regon) {
		toSerialize["regon"] = o.Regon
	}
	if !isNil(o.OwnerName) {
		toSerialize["ownerName"] = o.OwnerName
	}
	return toSerialize, nil
}

type NullableGetBusinessAccountResponse struct {
	value *GetBusinessAccountResponse
	isSet bool
}

func (v NullableGetBusinessAccountResponse) Get() *GetBusinessAccountResponse {
	return v.value
}

func (v *NullableGetBusinessAccountResponse) Set(val *GetBusinessAccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBusinessAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBusinessAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBusinessAccountResponse(val *GetBusinessAccountResponse) *NullableGetBusinessAccountResponse {
	return &NullableGetBusinessAccountResponse{value: val, isSet: true}
}

func (v NullableGetBusinessAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBusinessAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
