/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostBusinessAccountMenuImageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostBusinessAccountMenuImageResponse{}

// PostBusinessAccountMenuImageResponse struct for PostBusinessAccountMenuImageResponse
type PostBusinessAccountMenuImageResponse struct {
	ImageId *string `json:"imageId,omitempty"`
}

// NewPostBusinessAccountMenuImageResponse instantiates a new PostBusinessAccountMenuImageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostBusinessAccountMenuImageResponse() *PostBusinessAccountMenuImageResponse {
	this := PostBusinessAccountMenuImageResponse{}
	return &this
}

// NewPostBusinessAccountMenuImageResponseWithDefaults instantiates a new PostBusinessAccountMenuImageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostBusinessAccountMenuImageResponseWithDefaults() *PostBusinessAccountMenuImageResponse {
	this := PostBusinessAccountMenuImageResponse{}
	return &this
}

// GetImageId returns the ImageId field value if set, zero value otherwise.
func (o *PostBusinessAccountMenuImageResponse) GetImageId() string {
	if o == nil || isNil(o.ImageId) {
		var ret string
		return ret
	}
	return *o.ImageId
}

// GetImageIdOk returns a tuple with the ImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessAccountMenuImageResponse) GetImageIdOk() (*string, bool) {
	if o == nil || isNil(o.ImageId) {
		return nil, false
	}
	return o.ImageId, true
}

// HasImageId returns a boolean if a field has been set.
func (o *PostBusinessAccountMenuImageResponse) HasImageId() bool {
	if o != nil && !isNil(o.ImageId) {
		return true
	}

	return false
}

// SetImageId gets a reference to the given string and assigns it to the ImageId field.
func (o *PostBusinessAccountMenuImageResponse) SetImageId(v string) {
	o.ImageId = &v
}

func (o PostBusinessAccountMenuImageResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostBusinessAccountMenuImageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ImageId) {
		toSerialize["imageId"] = o.ImageId
	}
	return toSerialize, nil
}

type NullablePostBusinessAccountMenuImageResponse struct {
	value *PostBusinessAccountMenuImageResponse
	isSet bool
}

func (v NullablePostBusinessAccountMenuImageResponse) Get() *PostBusinessAccountMenuImageResponse {
	return v.value
}

func (v *NullablePostBusinessAccountMenuImageResponse) Set(val *PostBusinessAccountMenuImageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePostBusinessAccountMenuImageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePostBusinessAccountMenuImageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostBusinessAccountMenuImageResponse(val *PostBusinessAccountMenuImageResponse) *NullablePostBusinessAccountMenuImageResponse {
	return &NullablePostBusinessAccountMenuImageResponse{value: val, isSet: true}
}

func (v NullablePostBusinessAccountMenuImageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostBusinessAccountMenuImageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
