/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetBusinessAccountResponseAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBusinessAccountResponseAllOf{}

// GetBusinessAccountResponseAllOf struct for GetBusinessAccountResponseAllOf
type GetBusinessAccountResponseAllOf struct {
	Nip       *string `json:"nip,omitempty"`
	Krs       *string `json:"krs,omitempty"`
	Regon     *string `json:"regon,omitempty"`
	OwnerName *string `json:"ownerName,omitempty"`
}

// NewGetBusinessAccountResponseAllOf instantiates a new GetBusinessAccountResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBusinessAccountResponseAllOf() *GetBusinessAccountResponseAllOf {
	this := GetBusinessAccountResponseAllOf{}
	return &this
}

// NewGetBusinessAccountResponseAllOfWithDefaults instantiates a new GetBusinessAccountResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBusinessAccountResponseAllOfWithDefaults() *GetBusinessAccountResponseAllOf {
	this := GetBusinessAccountResponseAllOf{}
	return &this
}

// GetNip returns the Nip field value if set, zero value otherwise.
func (o *GetBusinessAccountResponseAllOf) GetNip() string {
	if o == nil || isNil(o.Nip) {
		var ret string
		return ret
	}
	return *o.Nip
}

// GetNipOk returns a tuple with the Nip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponseAllOf) GetNipOk() (*string, bool) {
	if o == nil || isNil(o.Nip) {
		return nil, false
	}
	return o.Nip, true
}

// HasNip returns a boolean if a field has been set.
func (o *GetBusinessAccountResponseAllOf) HasNip() bool {
	if o != nil && !isNil(o.Nip) {
		return true
	}

	return false
}

// SetNip gets a reference to the given string and assigns it to the Nip field.
func (o *GetBusinessAccountResponseAllOf) SetNip(v string) {
	o.Nip = &v
}

// GetKrs returns the Krs field value if set, zero value otherwise.
func (o *GetBusinessAccountResponseAllOf) GetKrs() string {
	if o == nil || isNil(o.Krs) {
		var ret string
		return ret
	}
	return *o.Krs
}

// GetKrsOk returns a tuple with the Krs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponseAllOf) GetKrsOk() (*string, bool) {
	if o == nil || isNil(o.Krs) {
		return nil, false
	}
	return o.Krs, true
}

// HasKrs returns a boolean if a field has been set.
func (o *GetBusinessAccountResponseAllOf) HasKrs() bool {
	if o != nil && !isNil(o.Krs) {
		return true
	}

	return false
}

// SetKrs gets a reference to the given string and assigns it to the Krs field.
func (o *GetBusinessAccountResponseAllOf) SetKrs(v string) {
	o.Krs = &v
}

// GetRegon returns the Regon field value if set, zero value otherwise.
func (o *GetBusinessAccountResponseAllOf) GetRegon() string {
	if o == nil || isNil(o.Regon) {
		var ret string
		return ret
	}
	return *o.Regon
}

// GetRegonOk returns a tuple with the Regon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponseAllOf) GetRegonOk() (*string, bool) {
	if o == nil || isNil(o.Regon) {
		return nil, false
	}
	return o.Regon, true
}

// HasRegon returns a boolean if a field has been set.
func (o *GetBusinessAccountResponseAllOf) HasRegon() bool {
	if o != nil && !isNil(o.Regon) {
		return true
	}

	return false
}

// SetRegon gets a reference to the given string and assigns it to the Regon field.
func (o *GetBusinessAccountResponseAllOf) SetRegon(v string) {
	o.Regon = &v
}

// GetOwnerName returns the OwnerName field value if set, zero value otherwise.
func (o *GetBusinessAccountResponseAllOf) GetOwnerName() string {
	if o == nil || isNil(o.OwnerName) {
		var ret string
		return ret
	}
	return *o.OwnerName
}

// GetOwnerNameOk returns a tuple with the OwnerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBusinessAccountResponseAllOf) GetOwnerNameOk() (*string, bool) {
	if o == nil || isNil(o.OwnerName) {
		return nil, false
	}
	return o.OwnerName, true
}

// HasOwnerName returns a boolean if a field has been set.
func (o *GetBusinessAccountResponseAllOf) HasOwnerName() bool {
	if o != nil && !isNil(o.OwnerName) {
		return true
	}

	return false
}

// SetOwnerName gets a reference to the given string and assigns it to the OwnerName field.
func (o *GetBusinessAccountResponseAllOf) SetOwnerName(v string) {
	o.OwnerName = &v
}

func (o GetBusinessAccountResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBusinessAccountResponseAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Nip) {
		toSerialize["nip"] = o.Nip
	}
	if !isNil(o.Krs) {
		toSerialize["krs"] = o.Krs
	}
	if !isNil(o.Regon) {
		toSerialize["regon"] = o.Regon
	}
	if !isNil(o.OwnerName) {
		toSerialize["ownerName"] = o.OwnerName
	}
	return toSerialize, nil
}

type NullableGetBusinessAccountResponseAllOf struct {
	value *GetBusinessAccountResponseAllOf
	isSet bool
}

func (v NullableGetBusinessAccountResponseAllOf) Get() *GetBusinessAccountResponseAllOf {
	return v.value
}

func (v *NullableGetBusinessAccountResponseAllOf) Set(val *GetBusinessAccountResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBusinessAccountResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBusinessAccountResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBusinessAccountResponseAllOf(val *GetBusinessAccountResponseAllOf) *NullableGetBusinessAccountResponseAllOf {
	return &NullableGetBusinessAccountResponseAllOf{value: val, isSet: true}
}

func (v NullableGetBusinessAccountResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBusinessAccountResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
