/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostUserVirtualCardTransactionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostUserVirtualCardTransactionRequest{}

// PostUserVirtualCardTransactionRequest struct for PostUserVirtualCardTransactionRequest
type PostUserVirtualCardTransactionRequest struct {
	ItemIds []string `json:"itemIds,omitempty"`
}

// NewPostUserVirtualCardTransactionRequest instantiates a new PostUserVirtualCardTransactionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostUserVirtualCardTransactionRequest() *PostUserVirtualCardTransactionRequest {
	this := PostUserVirtualCardTransactionRequest{}
	return &this
}

// NewPostUserVirtualCardTransactionRequestWithDefaults instantiates a new PostUserVirtualCardTransactionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostUserVirtualCardTransactionRequestWithDefaults() *PostUserVirtualCardTransactionRequest {
	this := PostUserVirtualCardTransactionRequest{}
	return &this
}

// GetItemIds returns the ItemIds field value if set, zero value otherwise.
func (o *PostUserVirtualCardTransactionRequest) GetItemIds() []string {
	if o == nil || isNil(o.ItemIds) {
		var ret []string
		return ret
	}
	return o.ItemIds
}

// GetItemIdsOk returns a tuple with the ItemIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostUserVirtualCardTransactionRequest) GetItemIdsOk() ([]string, bool) {
	if o == nil || isNil(o.ItemIds) {
		return nil, false
	}
	return o.ItemIds, true
}

// HasItemIds returns a boolean if a field has been set.
func (o *PostUserVirtualCardTransactionRequest) HasItemIds() bool {
	if o != nil && !isNil(o.ItemIds) {
		return true
	}

	return false
}

// SetItemIds gets a reference to the given []string and assigns it to the ItemIds field.
func (o *PostUserVirtualCardTransactionRequest) SetItemIds(v []string) {
	o.ItemIds = v
}

func (o PostUserVirtualCardTransactionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostUserVirtualCardTransactionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ItemIds) {
		toSerialize["itemIds"] = o.ItemIds
	}
	return toSerialize, nil
}

type NullablePostUserVirtualCardTransactionRequest struct {
	value *PostUserVirtualCardTransactionRequest
	isSet bool
}

func (v NullablePostUserVirtualCardTransactionRequest) Get() *PostUserVirtualCardTransactionRequest {
	return v.value
}

func (v *NullablePostUserVirtualCardTransactionRequest) Set(val *PostUserVirtualCardTransactionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostUserVirtualCardTransactionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostUserVirtualCardTransactionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostUserVirtualCardTransactionRequest(val *PostUserVirtualCardTransactionRequest) *NullablePostUserVirtualCardTransactionRequest {
	return &NullablePostUserVirtualCardTransactionRequest{value: val, isSet: true}
}

func (v NullablePostUserVirtualCardTransactionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostUserVirtualCardTransactionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
