/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostAccountEmailConfirmationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostAccountEmailConfirmationRequest{}

// PostAccountEmailConfirmationRequest struct for PostAccountEmailConfirmationRequest
type PostAccountEmailConfirmationRequest struct {
	Token *string `json:"token,omitempty" binding:"required"`
}

// NewPostAccountEmailConfirmationRequest instantiates a new PostAccountEmailConfirmationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostAccountEmailConfirmationRequest() *PostAccountEmailConfirmationRequest {
	this := PostAccountEmailConfirmationRequest{}
	return &this
}

// NewPostAccountEmailConfirmationRequestWithDefaults instantiates a new PostAccountEmailConfirmationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostAccountEmailConfirmationRequestWithDefaults() *PostAccountEmailConfirmationRequest {
	this := PostAccountEmailConfirmationRequest{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *PostAccountEmailConfirmationRequest) GetToken() string {
	if o == nil || isNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostAccountEmailConfirmationRequest) GetTokenOk() (*string, bool) {
	if o == nil || isNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *PostAccountEmailConfirmationRequest) HasToken() bool {
	if o != nil && !isNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *PostAccountEmailConfirmationRequest) SetToken(v string) {
	o.Token = &v
}

func (o PostAccountEmailConfirmationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostAccountEmailConfirmationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullablePostAccountEmailConfirmationRequest struct {
	value *PostAccountEmailConfirmationRequest
	isSet bool
}

func (v NullablePostAccountEmailConfirmationRequest) Get() *PostAccountEmailConfirmationRequest {
	return v.value
}

func (v *NullablePostAccountEmailConfirmationRequest) Set(val *PostAccountEmailConfirmationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostAccountEmailConfirmationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostAccountEmailConfirmationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostAccountEmailConfirmationRequest(val *PostAccountEmailConfirmationRequest) *NullablePostAccountEmailConfirmationRequest {
	return &NullablePostAccountEmailConfirmationRequest{value: val, isSet: true}
}

func (v NullablePostAccountEmailConfirmationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostAccountEmailConfirmationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
