/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PatchBusinessAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchBusinessAccountRequest{}

// PatchBusinessAccountRequest struct for PatchBusinessAccountRequest
type PatchBusinessAccountRequest struct {
	Name *string `json:"name,omitempty" binding:"required"`
}

// NewPatchBusinessAccountRequest instantiates a new PatchBusinessAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchBusinessAccountRequest() *PatchBusinessAccountRequest {
	this := PatchBusinessAccountRequest{}
	return &this
}

// NewPatchBusinessAccountRequestWithDefaults instantiates a new PatchBusinessAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchBusinessAccountRequestWithDefaults() *PatchBusinessAccountRequest {
	this := PatchBusinessAccountRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchBusinessAccountRequest) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchBusinessAccountRequest) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchBusinessAccountRequest) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchBusinessAccountRequest) SetName(v string) {
	o.Name = &v
}

func (o PatchBusinessAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchBusinessAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullablePatchBusinessAccountRequest struct {
	value *PatchBusinessAccountRequest
	isSet bool
}

func (v NullablePatchBusinessAccountRequest) Get() *PatchBusinessAccountRequest {
	return v.value
}

func (v *NullablePatchBusinessAccountRequest) Set(val *PatchBusinessAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchBusinessAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchBusinessAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchBusinessAccountRequest(val *PatchBusinessAccountRequest) *NullablePatchBusinessAccountRequest {
	return &NullablePatchBusinessAccountRequest{value: val, isSet: true}
}

func (v NullablePatchBusinessAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchBusinessAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
