/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetUserCardsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUserCardsResponse{}

// GetUserCardsResponse struct for GetUserCardsResponse
type GetUserCardsResponse struct {
	LocalCards   []LocalCardAPIModel        `json:"localCards,omitempty"`
	VirtualCards []ShortVirtualCardAPIModel `json:"virtualCards,omitempty"`
}

// NewGetUserCardsResponse instantiates a new GetUserCardsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserCardsResponse() *GetUserCardsResponse {
	this := GetUserCardsResponse{}
	return &this
}

// NewGetUserCardsResponseWithDefaults instantiates a new GetUserCardsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserCardsResponseWithDefaults() *GetUserCardsResponse {
	this := GetUserCardsResponse{}
	return &this
}

// GetLocalCards returns the LocalCards field value if set, zero value otherwise.
func (o *GetUserCardsResponse) GetLocalCards() []LocalCardAPIModel {
	if o == nil || isNil(o.LocalCards) {
		var ret []LocalCardAPIModel
		return ret
	}
	return o.LocalCards
}

// GetLocalCardsOk returns a tuple with the LocalCards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserCardsResponse) GetLocalCardsOk() ([]LocalCardAPIModel, bool) {
	if o == nil || isNil(o.LocalCards) {
		return nil, false
	}
	return o.LocalCards, true
}

// HasLocalCards returns a boolean if a field has been set.
func (o *GetUserCardsResponse) HasLocalCards() bool {
	if o != nil && !isNil(o.LocalCards) {
		return true
	}

	return false
}

// SetLocalCards gets a reference to the given []LocalCardAPIModel and assigns it to the LocalCards field.
func (o *GetUserCardsResponse) SetLocalCards(v []LocalCardAPIModel) {
	o.LocalCards = v
}

// GetVirtualCards returns the VirtualCards field value if set, zero value otherwise.
func (o *GetUserCardsResponse) GetVirtualCards() []ShortVirtualCardAPIModel {
	if o == nil || isNil(o.VirtualCards) {
		var ret []ShortVirtualCardAPIModel
		return ret
	}
	return o.VirtualCards
}

// GetVirtualCardsOk returns a tuple with the VirtualCards field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserCardsResponse) GetVirtualCardsOk() ([]ShortVirtualCardAPIModel, bool) {
	if o == nil || isNil(o.VirtualCards) {
		return nil, false
	}
	return o.VirtualCards, true
}

// HasVirtualCards returns a boolean if a field has been set.
func (o *GetUserCardsResponse) HasVirtualCards() bool {
	if o != nil && !isNil(o.VirtualCards) {
		return true
	}

	return false
}

// SetVirtualCards gets a reference to the given []ShortVirtualCardAPIModel and assigns it to the VirtualCards field.
func (o *GetUserCardsResponse) SetVirtualCards(v []ShortVirtualCardAPIModel) {
	o.VirtualCards = v
}

func (o GetUserCardsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUserCardsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.LocalCards) {
		toSerialize["localCards"] = o.LocalCards
	}
	if !isNil(o.VirtualCards) {
		toSerialize["virtualCards"] = o.VirtualCards
	}
	return toSerialize, nil
}

type NullableGetUserCardsResponse struct {
	value *GetUserCardsResponse
	isSet bool
}

func (v NullableGetUserCardsResponse) Get() *GetUserCardsResponse {
	return v.value
}

func (v *NullableGetUserCardsResponse) Set(val *GetUserCardsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserCardsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserCardsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserCardsResponse(val *GetUserCardsResponse) *NullableGetUserCardsResponse {
	return &NullableGetUserCardsResponse{value: val, isSet: true}
}

func (v NullableGetUserCardsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserCardsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
