/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ShortBusinessDetailsAPIModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShortBusinessDetailsAPIModel{}

// ShortBusinessDetailsAPIModel struct for ShortBusinessDetailsAPIModel
type ShortBusinessDetailsAPIModel struct {
	PublicId       *string `json:"publicId,omitempty"`
	Name           *string `json:"name,omitempty"`
	Description    *string `json:"description,omitempty"`
	GpsCoordinates *string `json:"gpsCoordinates,omitempty"`
	BannerImageId  *string `json:"bannerImageId,omitempty"`
	IconImageId    *string `json:"iconImageId,omitempty"`
}

// NewShortBusinessDetailsAPIModel instantiates a new ShortBusinessDetailsAPIModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShortBusinessDetailsAPIModel() *ShortBusinessDetailsAPIModel {
	this := ShortBusinessDetailsAPIModel{}
	return &this
}

// NewShortBusinessDetailsAPIModelWithDefaults instantiates a new ShortBusinessDetailsAPIModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShortBusinessDetailsAPIModelWithDefaults() *ShortBusinessDetailsAPIModel {
	this := ShortBusinessDetailsAPIModel{}
	return &this
}

// GetPublicId returns the PublicId field value if set, zero value otherwise.
func (o *ShortBusinessDetailsAPIModel) GetPublicId() string {
	if o == nil || isNil(o.PublicId) {
		var ret string
		return ret
	}
	return *o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShortBusinessDetailsAPIModel) GetPublicIdOk() (*string, bool) {
	if o == nil || isNil(o.PublicId) {
		return nil, false
	}
	return o.PublicId, true
}

// HasPublicId returns a boolean if a field has been set.
func (o *ShortBusinessDetailsAPIModel) HasPublicId() bool {
	if o != nil && !isNil(o.PublicId) {
		return true
	}

	return false
}

// SetPublicId gets a reference to the given string and assigns it to the PublicId field.
func (o *ShortBusinessDetailsAPIModel) SetPublicId(v string) {
	o.PublicId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ShortBusinessDetailsAPIModel) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShortBusinessDetailsAPIModel) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ShortBusinessDetailsAPIModel) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ShortBusinessDetailsAPIModel) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ShortBusinessDetailsAPIModel) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShortBusinessDetailsAPIModel) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ShortBusinessDetailsAPIModel) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ShortBusinessDetailsAPIModel) SetDescription(v string) {
	o.Description = &v
}

// GetGpsCoordinates returns the GpsCoordinates field value if set, zero value otherwise.
func (o *ShortBusinessDetailsAPIModel) GetGpsCoordinates() string {
	if o == nil || isNil(o.GpsCoordinates) {
		var ret string
		return ret
	}
	return *o.GpsCoordinates
}

// GetGpsCoordinatesOk returns a tuple with the GpsCoordinates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShortBusinessDetailsAPIModel) GetGpsCoordinatesOk() (*string, bool) {
	if o == nil || isNil(o.GpsCoordinates) {
		return nil, false
	}
	return o.GpsCoordinates, true
}

// HasGpsCoordinates returns a boolean if a field has been set.
func (o *ShortBusinessDetailsAPIModel) HasGpsCoordinates() bool {
	if o != nil && !isNil(o.GpsCoordinates) {
		return true
	}

	return false
}

// SetGpsCoordinates gets a reference to the given string and assigns it to the GpsCoordinates field.
func (o *ShortBusinessDetailsAPIModel) SetGpsCoordinates(v string) {
	o.GpsCoordinates = &v
}

// GetBannerImageId returns the BannerImageId field value if set, zero value otherwise.
func (o *ShortBusinessDetailsAPIModel) GetBannerImageId() string {
	if o == nil || isNil(o.BannerImageId) {
		var ret string
		return ret
	}
	return *o.BannerImageId
}

// GetBannerImageIdOk returns a tuple with the BannerImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShortBusinessDetailsAPIModel) GetBannerImageIdOk() (*string, bool) {
	if o == nil || isNil(o.BannerImageId) {
		return nil, false
	}
	return o.BannerImageId, true
}

// HasBannerImageId returns a boolean if a field has been set.
func (o *ShortBusinessDetailsAPIModel) HasBannerImageId() bool {
	if o != nil && !isNil(o.BannerImageId) {
		return true
	}

	return false
}

// SetBannerImageId gets a reference to the given string and assigns it to the BannerImageId field.
func (o *ShortBusinessDetailsAPIModel) SetBannerImageId(v string) {
	o.BannerImageId = &v
}

// GetIconImageId returns the IconImageId field value if set, zero value otherwise.
func (o *ShortBusinessDetailsAPIModel) GetIconImageId() string {
	if o == nil || isNil(o.IconImageId) {
		var ret string
		return ret
	}
	return *o.IconImageId
}

// GetIconImageIdOk returns a tuple with the IconImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShortBusinessDetailsAPIModel) GetIconImageIdOk() (*string, bool) {
	if o == nil || isNil(o.IconImageId) {
		return nil, false
	}
	return o.IconImageId, true
}

// HasIconImageId returns a boolean if a field has been set.
func (o *ShortBusinessDetailsAPIModel) HasIconImageId() bool {
	if o != nil && !isNil(o.IconImageId) {
		return true
	}

	return false
}

// SetIconImageId gets a reference to the given string and assigns it to the IconImageId field.
func (o *ShortBusinessDetailsAPIModel) SetIconImageId(v string) {
	o.IconImageId = &v
}

func (o ShortBusinessDetailsAPIModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShortBusinessDetailsAPIModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PublicId) {
		toSerialize["publicId"] = o.PublicId
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.GpsCoordinates) {
		toSerialize["gpsCoordinates"] = o.GpsCoordinates
	}
	if !isNil(o.BannerImageId) {
		toSerialize["bannerImageId"] = o.BannerImageId
	}
	if !isNil(o.IconImageId) {
		toSerialize["iconImageId"] = o.IconImageId
	}
	return toSerialize, nil
}

type NullableShortBusinessDetailsAPIModel struct {
	value *ShortBusinessDetailsAPIModel
	isSet bool
}

func (v NullableShortBusinessDetailsAPIModel) Get() *ShortBusinessDetailsAPIModel {
	return v.value
}

func (v *NullableShortBusinessDetailsAPIModel) Set(val *ShortBusinessDetailsAPIModel) {
	v.value = val
	v.isSet = true
}

func (v NullableShortBusinessDetailsAPIModel) IsSet() bool {
	return v.isSet
}

func (v *NullableShortBusinessDetailsAPIModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShortBusinessDetailsAPIModel(val *ShortBusinessDetailsAPIModel) *NullableShortBusinessDetailsAPIModel {
	return &NullableShortBusinessDetailsAPIModel{value: val, isSet: true}
}

func (v NullableShortBusinessDetailsAPIModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShortBusinessDetailsAPIModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
