/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostBusinessTransactionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostBusinessTransactionRequest{}

// PostBusinessTransactionRequest struct for PostBusinessTransactionRequest
type PostBusinessTransactionRequest struct {
	AddedPoints *int32               `json:"addedPoints,omitempty"`
	ItemActions []ItemActionAPIModel `json:"itemActions,omitempty"`
}

// NewPostBusinessTransactionRequest instantiates a new PostBusinessTransactionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostBusinessTransactionRequest() *PostBusinessTransactionRequest {
	this := PostBusinessTransactionRequest{}
	return &this
}

// NewPostBusinessTransactionRequestWithDefaults instantiates a new PostBusinessTransactionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostBusinessTransactionRequestWithDefaults() *PostBusinessTransactionRequest {
	this := PostBusinessTransactionRequest{}
	return &this
}

// GetAddedPoints returns the AddedPoints field value if set, zero value otherwise.
func (o *PostBusinessTransactionRequest) GetAddedPoints() int32 {
	if o == nil || isNil(o.AddedPoints) {
		var ret int32
		return ret
	}
	return *o.AddedPoints
}

// GetAddedPointsOk returns a tuple with the AddedPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessTransactionRequest) GetAddedPointsOk() (*int32, bool) {
	if o == nil || isNil(o.AddedPoints) {
		return nil, false
	}
	return o.AddedPoints, true
}

// HasAddedPoints returns a boolean if a field has been set.
func (o *PostBusinessTransactionRequest) HasAddedPoints() bool {
	if o != nil && !isNil(o.AddedPoints) {
		return true
	}

	return false
}

// SetAddedPoints gets a reference to the given int32 and assigns it to the AddedPoints field.
func (o *PostBusinessTransactionRequest) SetAddedPoints(v int32) {
	o.AddedPoints = &v
}

// GetItemActions returns the ItemActions field value if set, zero value otherwise.
func (o *PostBusinessTransactionRequest) GetItemActions() []ItemActionAPIModel {
	if o == nil || isNil(o.ItemActions) {
		var ret []ItemActionAPIModel
		return ret
	}
	return o.ItemActions
}

// GetItemActionsOk returns a tuple with the ItemActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessTransactionRequest) GetItemActionsOk() ([]ItemActionAPIModel, bool) {
	if o == nil || isNil(o.ItemActions) {
		return nil, false
	}
	return o.ItemActions, true
}

// HasItemActions returns a boolean if a field has been set.
func (o *PostBusinessTransactionRequest) HasItemActions() bool {
	if o != nil && !isNil(o.ItemActions) {
		return true
	}

	return false
}

// SetItemActions gets a reference to the given []ItemActionAPIModel and assigns it to the ItemActions field.
func (o *PostBusinessTransactionRequest) SetItemActions(v []ItemActionAPIModel) {
	o.ItemActions = v
}

func (o PostBusinessTransactionRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostBusinessTransactionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AddedPoints) {
		toSerialize["addedPoints"] = o.AddedPoints
	}
	if !isNil(o.ItemActions) {
		toSerialize["itemActions"] = o.ItemActions
	}
	return toSerialize, nil
}

type NullablePostBusinessTransactionRequest struct {
	value *PostBusinessTransactionRequest
	isSet bool
}

func (v NullablePostBusinessTransactionRequest) Get() *PostBusinessTransactionRequest {
	return v.value
}

func (v *NullablePostBusinessTransactionRequest) Set(val *PostBusinessTransactionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostBusinessTransactionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostBusinessTransactionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostBusinessTransactionRequest(val *PostBusinessTransactionRequest) *NullablePostBusinessTransactionRequest {
	return &NullablePostBusinessTransactionRequest{value: val, isSet: true}
}

func (v NullablePostBusinessTransactionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostBusinessTransactionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
