/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostBusinessAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostBusinessAccountRequest{}

// PostBusinessAccountRequest struct for PostBusinessAccountRequest
type PostBusinessAccountRequest struct {
	Name           *string `json:"name,omitempty"`
	Address        *string `json:"address,omitempty"`
	GpsCoordinates *string `json:"gpsCoordinates,omitempty"`
	Nip            *string `json:"nip,omitempty"`
	Krs            *string `json:"krs,omitempty"`
	Regon          *string `json:"regon,omitempty"`
	OwnerName      *string `json:"ownerName,omitempty"`
}

// NewPostBusinessAccountRequest instantiates a new PostBusinessAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostBusinessAccountRequest() *PostBusinessAccountRequest {
	this := PostBusinessAccountRequest{}
	return &this
}

// NewPostBusinessAccountRequestWithDefaults instantiates a new PostBusinessAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostBusinessAccountRequestWithDefaults() *PostBusinessAccountRequest {
	this := PostBusinessAccountRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PostBusinessAccountRequest) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessAccountRequest) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PostBusinessAccountRequest) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PostBusinessAccountRequest) SetName(v string) {
	o.Name = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *PostBusinessAccountRequest) GetAddress() string {
	if o == nil || isNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessAccountRequest) GetAddressOk() (*string, bool) {
	if o == nil || isNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *PostBusinessAccountRequest) HasAddress() bool {
	if o != nil && !isNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *PostBusinessAccountRequest) SetAddress(v string) {
	o.Address = &v
}

// GetGpsCoordinates returns the GpsCoordinates field value if set, zero value otherwise.
func (o *PostBusinessAccountRequest) GetGpsCoordinates() string {
	if o == nil || isNil(o.GpsCoordinates) {
		var ret string
		return ret
	}
	return *o.GpsCoordinates
}

// GetGpsCoordinatesOk returns a tuple with the GpsCoordinates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessAccountRequest) GetGpsCoordinatesOk() (*string, bool) {
	if o == nil || isNil(o.GpsCoordinates) {
		return nil, false
	}
	return o.GpsCoordinates, true
}

// HasGpsCoordinates returns a boolean if a field has been set.
func (o *PostBusinessAccountRequest) HasGpsCoordinates() bool {
	if o != nil && !isNil(o.GpsCoordinates) {
		return true
	}

	return false
}

// SetGpsCoordinates gets a reference to the given string and assigns it to the GpsCoordinates field.
func (o *PostBusinessAccountRequest) SetGpsCoordinates(v string) {
	o.GpsCoordinates = &v
}

// GetNip returns the Nip field value if set, zero value otherwise.
func (o *PostBusinessAccountRequest) GetNip() string {
	if o == nil || isNil(o.Nip) {
		var ret string
		return ret
	}
	return *o.Nip
}

// GetNipOk returns a tuple with the Nip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessAccountRequest) GetNipOk() (*string, bool) {
	if o == nil || isNil(o.Nip) {
		return nil, false
	}
	return o.Nip, true
}

// HasNip returns a boolean if a field has been set.
func (o *PostBusinessAccountRequest) HasNip() bool {
	if o != nil && !isNil(o.Nip) {
		return true
	}

	return false
}

// SetNip gets a reference to the given string and assigns it to the Nip field.
func (o *PostBusinessAccountRequest) SetNip(v string) {
	o.Nip = &v
}

// GetKrs returns the Krs field value if set, zero value otherwise.
func (o *PostBusinessAccountRequest) GetKrs() string {
	if o == nil || isNil(o.Krs) {
		var ret string
		return ret
	}
	return *o.Krs
}

// GetKrsOk returns a tuple with the Krs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessAccountRequest) GetKrsOk() (*string, bool) {
	if o == nil || isNil(o.Krs) {
		return nil, false
	}
	return o.Krs, true
}

// HasKrs returns a boolean if a field has been set.
func (o *PostBusinessAccountRequest) HasKrs() bool {
	if o != nil && !isNil(o.Krs) {
		return true
	}

	return false
}

// SetKrs gets a reference to the given string and assigns it to the Krs field.
func (o *PostBusinessAccountRequest) SetKrs(v string) {
	o.Krs = &v
}

// GetRegon returns the Regon field value if set, zero value otherwise.
func (o *PostBusinessAccountRequest) GetRegon() string {
	if o == nil || isNil(o.Regon) {
		var ret string
		return ret
	}
	return *o.Regon
}

// GetRegonOk returns a tuple with the Regon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessAccountRequest) GetRegonOk() (*string, bool) {
	if o == nil || isNil(o.Regon) {
		return nil, false
	}
	return o.Regon, true
}

// HasRegon returns a boolean if a field has been set.
func (o *PostBusinessAccountRequest) HasRegon() bool {
	if o != nil && !isNil(o.Regon) {
		return true
	}

	return false
}

// SetRegon gets a reference to the given string and assigns it to the Regon field.
func (o *PostBusinessAccountRequest) SetRegon(v string) {
	o.Regon = &v
}

// GetOwnerName returns the OwnerName field value if set, zero value otherwise.
func (o *PostBusinessAccountRequest) GetOwnerName() string {
	if o == nil || isNil(o.OwnerName) {
		var ret string
		return ret
	}
	return *o.OwnerName
}

// GetOwnerNameOk returns a tuple with the OwnerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessAccountRequest) GetOwnerNameOk() (*string, bool) {
	if o == nil || isNil(o.OwnerName) {
		return nil, false
	}
	return o.OwnerName, true
}

// HasOwnerName returns a boolean if a field has been set.
func (o *PostBusinessAccountRequest) HasOwnerName() bool {
	if o != nil && !isNil(o.OwnerName) {
		return true
	}

	return false
}

// SetOwnerName gets a reference to the given string and assigns it to the OwnerName field.
func (o *PostBusinessAccountRequest) SetOwnerName(v string) {
	o.OwnerName = &v
}

func (o PostBusinessAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostBusinessAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !isNil(o.GpsCoordinates) {
		toSerialize["gpsCoordinates"] = o.GpsCoordinates
	}
	if !isNil(o.Nip) {
		toSerialize["nip"] = o.Nip
	}
	if !isNil(o.Krs) {
		toSerialize["krs"] = o.Krs
	}
	if !isNil(o.Regon) {
		toSerialize["regon"] = o.Regon
	}
	if !isNil(o.OwnerName) {
		toSerialize["ownerName"] = o.OwnerName
	}
	return toSerialize, nil
}

type NullablePostBusinessAccountRequest struct {
	value *PostBusinessAccountRequest
	isSet bool
}

func (v NullablePostBusinessAccountRequest) Get() *PostBusinessAccountRequest {
	return v.value
}

func (v *NullablePostBusinessAccountRequest) Set(val *PostBusinessAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostBusinessAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostBusinessAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostBusinessAccountRequest(val *PostBusinessAccountRequest) *NullablePostBusinessAccountRequest {
	return &NullablePostBusinessAccountRequest{value: val, isSet: true}
}

func (v NullablePostBusinessAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostBusinessAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
