/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PublicBusinessDetailsAPIModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicBusinessDetailsAPIModel{}

// PublicBusinessDetailsAPIModel struct for PublicBusinessDetailsAPIModel
type PublicBusinessDetailsAPIModel struct {
	PublicId        *string                  `json:"publicId,omitempty"`
	Name            *string                  `json:"name,omitempty"`
	Address         *string                  `json:"address,omitempty"`
	GpsCoordinates  *string                  `json:"gpsCoordinates,omitempty"`
	BannerImageId   *string                  `json:"bannerImageId,omitempty"`
	Description     string                   `json:"description"`
	IconImageId     *string                  `json:"iconImageId,omitempty"`
	MenuImageIds    []string                 `json:"menuImageIds,omitempty"`
	ItemDefinitions []ItemDefinitionAPIModel `json:"itemDefinitions,omitempty"`
}

// NewPublicBusinessDetailsAPIModel instantiates a new PublicBusinessDetailsAPIModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicBusinessDetailsAPIModel(description string) *PublicBusinessDetailsAPIModel {
	this := PublicBusinessDetailsAPIModel{}
	this.Description = description
	return &this
}

// NewPublicBusinessDetailsAPIModelWithDefaults instantiates a new PublicBusinessDetailsAPIModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicBusinessDetailsAPIModelWithDefaults() *PublicBusinessDetailsAPIModel {
	this := PublicBusinessDetailsAPIModel{}
	return &this
}

// GetPublicId returns the PublicId field value if set, zero value otherwise.
func (o *PublicBusinessDetailsAPIModel) GetPublicId() string {
	if o == nil || isNil(o.PublicId) {
		var ret string
		return ret
	}
	return *o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicBusinessDetailsAPIModel) GetPublicIdOk() (*string, bool) {
	if o == nil || isNil(o.PublicId) {
		return nil, false
	}
	return o.PublicId, true
}

// HasPublicId returns a boolean if a field has been set.
func (o *PublicBusinessDetailsAPIModel) HasPublicId() bool {
	if o != nil && !isNil(o.PublicId) {
		return true
	}

	return false
}

// SetPublicId gets a reference to the given string and assigns it to the PublicId field.
func (o *PublicBusinessDetailsAPIModel) SetPublicId(v string) {
	o.PublicId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PublicBusinessDetailsAPIModel) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicBusinessDetailsAPIModel) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PublicBusinessDetailsAPIModel) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PublicBusinessDetailsAPIModel) SetName(v string) {
	o.Name = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *PublicBusinessDetailsAPIModel) GetAddress() string {
	if o == nil || isNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicBusinessDetailsAPIModel) GetAddressOk() (*string, bool) {
	if o == nil || isNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *PublicBusinessDetailsAPIModel) HasAddress() bool {
	if o != nil && !isNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *PublicBusinessDetailsAPIModel) SetAddress(v string) {
	o.Address = &v
}

// GetGpsCoordinates returns the GpsCoordinates field value if set, zero value otherwise.
func (o *PublicBusinessDetailsAPIModel) GetGpsCoordinates() string {
	if o == nil || isNil(o.GpsCoordinates) {
		var ret string
		return ret
	}
	return *o.GpsCoordinates
}

// GetGpsCoordinatesOk returns a tuple with the GpsCoordinates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicBusinessDetailsAPIModel) GetGpsCoordinatesOk() (*string, bool) {
	if o == nil || isNil(o.GpsCoordinates) {
		return nil, false
	}
	return o.GpsCoordinates, true
}

// HasGpsCoordinates returns a boolean if a field has been set.
func (o *PublicBusinessDetailsAPIModel) HasGpsCoordinates() bool {
	if o != nil && !isNil(o.GpsCoordinates) {
		return true
	}

	return false
}

// SetGpsCoordinates gets a reference to the given string and assigns it to the GpsCoordinates field.
func (o *PublicBusinessDetailsAPIModel) SetGpsCoordinates(v string) {
	o.GpsCoordinates = &v
}

// GetBannerImageId returns the BannerImageId field value if set, zero value otherwise.
func (o *PublicBusinessDetailsAPIModel) GetBannerImageId() string {
	if o == nil || isNil(o.BannerImageId) {
		var ret string
		return ret
	}
	return *o.BannerImageId
}

// GetBannerImageIdOk returns a tuple with the BannerImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicBusinessDetailsAPIModel) GetBannerImageIdOk() (*string, bool) {
	if o == nil || isNil(o.BannerImageId) {
		return nil, false
	}
	return o.BannerImageId, true
}

// HasBannerImageId returns a boolean if a field has been set.
func (o *PublicBusinessDetailsAPIModel) HasBannerImageId() bool {
	if o != nil && !isNil(o.BannerImageId) {
		return true
	}

	return false
}

// SetBannerImageId gets a reference to the given string and assigns it to the BannerImageId field.
func (o *PublicBusinessDetailsAPIModel) SetBannerImageId(v string) {
	o.BannerImageId = &v
}

// GetDescription returns the Description field value
func (o *PublicBusinessDetailsAPIModel) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *PublicBusinessDetailsAPIModel) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PublicBusinessDetailsAPIModel) SetDescription(v string) {
	o.Description = v
}

// GetIconImageId returns the IconImageId field value if set, zero value otherwise.
func (o *PublicBusinessDetailsAPIModel) GetIconImageId() string {
	if o == nil || isNil(o.IconImageId) {
		var ret string
		return ret
	}
	return *o.IconImageId
}

// GetIconImageIdOk returns a tuple with the IconImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicBusinessDetailsAPIModel) GetIconImageIdOk() (*string, bool) {
	if o == nil || isNil(o.IconImageId) {
		return nil, false
	}
	return o.IconImageId, true
}

// HasIconImageId returns a boolean if a field has been set.
func (o *PublicBusinessDetailsAPIModel) HasIconImageId() bool {
	if o != nil && !isNil(o.IconImageId) {
		return true
	}

	return false
}

// SetIconImageId gets a reference to the given string and assigns it to the IconImageId field.
func (o *PublicBusinessDetailsAPIModel) SetIconImageId(v string) {
	o.IconImageId = &v
}

// GetMenuImageIds returns the MenuImageIds field value if set, zero value otherwise.
func (o *PublicBusinessDetailsAPIModel) GetMenuImageIds() []string {
	if o == nil || isNil(o.MenuImageIds) {
		var ret []string
		return ret
	}
	return o.MenuImageIds
}

// GetMenuImageIdsOk returns a tuple with the MenuImageIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicBusinessDetailsAPIModel) GetMenuImageIdsOk() ([]string, bool) {
	if o == nil || isNil(o.MenuImageIds) {
		return nil, false
	}
	return o.MenuImageIds, true
}

// HasMenuImageIds returns a boolean if a field has been set.
func (o *PublicBusinessDetailsAPIModel) HasMenuImageIds() bool {
	if o != nil && !isNil(o.MenuImageIds) {
		return true
	}

	return false
}

// SetMenuImageIds gets a reference to the given []string and assigns it to the MenuImageIds field.
func (o *PublicBusinessDetailsAPIModel) SetMenuImageIds(v []string) {
	o.MenuImageIds = v
}

// GetItemDefinitions returns the ItemDefinitions field value if set, zero value otherwise.
func (o *PublicBusinessDetailsAPIModel) GetItemDefinitions() []ItemDefinitionAPIModel {
	if o == nil || isNil(o.ItemDefinitions) {
		var ret []ItemDefinitionAPIModel
		return ret
	}
	return o.ItemDefinitions
}

// GetItemDefinitionsOk returns a tuple with the ItemDefinitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicBusinessDetailsAPIModel) GetItemDefinitionsOk() ([]ItemDefinitionAPIModel, bool) {
	if o == nil || isNil(o.ItemDefinitions) {
		return nil, false
	}
	return o.ItemDefinitions, true
}

// HasItemDefinitions returns a boolean if a field has been set.
func (o *PublicBusinessDetailsAPIModel) HasItemDefinitions() bool {
	if o != nil && !isNil(o.ItemDefinitions) {
		return true
	}

	return false
}

// SetItemDefinitions gets a reference to the given []ItemDefinitionAPIModel and assigns it to the ItemDefinitions field.
func (o *PublicBusinessDetailsAPIModel) SetItemDefinitions(v []ItemDefinitionAPIModel) {
	o.ItemDefinitions = v
}

func (o PublicBusinessDetailsAPIModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicBusinessDetailsAPIModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PublicId) {
		toSerialize["publicId"] = o.PublicId
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !isNil(o.GpsCoordinates) {
		toSerialize["gpsCoordinates"] = o.GpsCoordinates
	}
	if !isNil(o.BannerImageId) {
		toSerialize["bannerImageId"] = o.BannerImageId
	}
	toSerialize["description"] = o.Description
	if !isNil(o.IconImageId) {
		toSerialize["iconImageId"] = o.IconImageId
	}
	if !isNil(o.MenuImageIds) {
		toSerialize["menuImageIds"] = o.MenuImageIds
	}
	if !isNil(o.ItemDefinitions) {
		toSerialize["itemDefinitions"] = o.ItemDefinitions
	}
	return toSerialize, nil
}

type NullablePublicBusinessDetailsAPIModel struct {
	value *PublicBusinessDetailsAPIModel
	isSet bool
}

func (v NullablePublicBusinessDetailsAPIModel) Get() *PublicBusinessDetailsAPIModel {
	return v.value
}

func (v *NullablePublicBusinessDetailsAPIModel) Set(val *PublicBusinessDetailsAPIModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicBusinessDetailsAPIModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicBusinessDetailsAPIModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicBusinessDetailsAPIModel(val *PublicBusinessDetailsAPIModel) *NullablePublicBusinessDetailsAPIModel {
	return &NullablePublicBusinessDetailsAPIModel{value: val, isSet: true}
}

func (v NullablePublicBusinessDetailsAPIModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicBusinessDetailsAPIModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
