/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostUserVirtualCardItemResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostUserVirtualCardItemResponse{}

// PostUserVirtualCardItemResponse struct for PostUserVirtualCardItemResponse
type PostUserVirtualCardItemResponse struct {
	ItemId *string `json:"itemId,omitempty"`
}

// NewPostUserVirtualCardItemResponse instantiates a new PostUserVirtualCardItemResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostUserVirtualCardItemResponse() *PostUserVirtualCardItemResponse {
	this := PostUserVirtualCardItemResponse{}
	return &this
}

// NewPostUserVirtualCardItemResponseWithDefaults instantiates a new PostUserVirtualCardItemResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostUserVirtualCardItemResponseWithDefaults() *PostUserVirtualCardItemResponse {
	this := PostUserVirtualCardItemResponse{}
	return &this
}

// GetItemId returns the ItemId field value if set, zero value otherwise.
func (o *PostUserVirtualCardItemResponse) GetItemId() string {
	if o == nil || isNil(o.ItemId) {
		var ret string
		return ret
	}
	return *o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostUserVirtualCardItemResponse) GetItemIdOk() (*string, bool) {
	if o == nil || isNil(o.ItemId) {
		return nil, false
	}
	return o.ItemId, true
}

// HasItemId returns a boolean if a field has been set.
func (o *PostUserVirtualCardItemResponse) HasItemId() bool {
	if o != nil && !isNil(o.ItemId) {
		return true
	}

	return false
}

// SetItemId gets a reference to the given string and assigns it to the ItemId field.
func (o *PostUserVirtualCardItemResponse) SetItemId(v string) {
	o.ItemId = &v
}

func (o PostUserVirtualCardItemResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostUserVirtualCardItemResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ItemId) {
		toSerialize["itemId"] = o.ItemId
	}
	return toSerialize, nil
}

type NullablePostUserVirtualCardItemResponse struct {
	value *PostUserVirtualCardItemResponse
	isSet bool
}

func (v NullablePostUserVirtualCardItemResponse) Get() *PostUserVirtualCardItemResponse {
	return v.value
}

func (v *NullablePostUserVirtualCardItemResponse) Set(val *PostUserVirtualCardItemResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePostUserVirtualCardItemResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePostUserVirtualCardItemResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostUserVirtualCardItemResponse(val *PostUserVirtualCardItemResponse) *NullablePostUserVirtualCardItemResponse {
	return &NullablePostUserVirtualCardItemResponse{value: val, isSet: true}
}

func (v NullablePostUserVirtualCardItemResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostUserVirtualCardItemResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
