/*
StampWallet API Server

StampWallet API Server REST Specification

API version: 0.1.0
Contact: fbstachura@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostBusinessAccountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostBusinessAccountResponse{}

// PostBusinessAccountResponse struct for PostBusinessAccountResponse
type PostBusinessAccountResponse struct {
	PublicId      *string `json:"publicId,omitempty"`
	BannerImageId *string `json:"bannerImageId,omitempty"`
	IconImageId   *string `json:"iconImageId,omitempty"`
}

// NewPostBusinessAccountResponse instantiates a new PostBusinessAccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostBusinessAccountResponse() *PostBusinessAccountResponse {
	this := PostBusinessAccountResponse{}
	return &this
}

// NewPostBusinessAccountResponseWithDefaults instantiates a new PostBusinessAccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostBusinessAccountResponseWithDefaults() *PostBusinessAccountResponse {
	this := PostBusinessAccountResponse{}
	return &this
}

// GetPublicId returns the PublicId field value if set, zero value otherwise.
func (o *PostBusinessAccountResponse) GetPublicId() string {
	if o == nil || isNil(o.PublicId) {
		var ret string
		return ret
	}
	return *o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessAccountResponse) GetPublicIdOk() (*string, bool) {
	if o == nil || isNil(o.PublicId) {
		return nil, false
	}
	return o.PublicId, true
}

// HasPublicId returns a boolean if a field has been set.
func (o *PostBusinessAccountResponse) HasPublicId() bool {
	if o != nil && !isNil(o.PublicId) {
		return true
	}

	return false
}

// SetPublicId gets a reference to the given string and assigns it to the PublicId field.
func (o *PostBusinessAccountResponse) SetPublicId(v string) {
	o.PublicId = &v
}

// GetBannerImageId returns the BannerImageId field value if set, zero value otherwise.
func (o *PostBusinessAccountResponse) GetBannerImageId() string {
	if o == nil || isNil(o.BannerImageId) {
		var ret string
		return ret
	}
	return *o.BannerImageId
}

// GetBannerImageIdOk returns a tuple with the BannerImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessAccountResponse) GetBannerImageIdOk() (*string, bool) {
	if o == nil || isNil(o.BannerImageId) {
		return nil, false
	}
	return o.BannerImageId, true
}

// HasBannerImageId returns a boolean if a field has been set.
func (o *PostBusinessAccountResponse) HasBannerImageId() bool {
	if o != nil && !isNil(o.BannerImageId) {
		return true
	}

	return false
}

// SetBannerImageId gets a reference to the given string and assigns it to the BannerImageId field.
func (o *PostBusinessAccountResponse) SetBannerImageId(v string) {
	o.BannerImageId = &v
}

// GetIconImageId returns the IconImageId field value if set, zero value otherwise.
func (o *PostBusinessAccountResponse) GetIconImageId() string {
	if o == nil || isNil(o.IconImageId) {
		var ret string
		return ret
	}
	return *o.IconImageId
}

// GetIconImageIdOk returns a tuple with the IconImageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostBusinessAccountResponse) GetIconImageIdOk() (*string, bool) {
	if o == nil || isNil(o.IconImageId) {
		return nil, false
	}
	return o.IconImageId, true
}

// HasIconImageId returns a boolean if a field has been set.
func (o *PostBusinessAccountResponse) HasIconImageId() bool {
	if o != nil && !isNil(o.IconImageId) {
		return true
	}

	return false
}

// SetIconImageId gets a reference to the given string and assigns it to the IconImageId field.
func (o *PostBusinessAccountResponse) SetIconImageId(v string) {
	o.IconImageId = &v
}

func (o PostBusinessAccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostBusinessAccountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.PublicId) {
		toSerialize["publicId"] = o.PublicId
	}
	if !isNil(o.BannerImageId) {
		toSerialize["bannerImageId"] = o.BannerImageId
	}
	if !isNil(o.IconImageId) {
		toSerialize["iconImageId"] = o.IconImageId
	}
	return toSerialize, nil
}

type NullablePostBusinessAccountResponse struct {
	value *PostBusinessAccountResponse
	isSet bool
}

func (v NullablePostBusinessAccountResponse) Get() *PostBusinessAccountResponse {
	return v.value
}

func (v *NullablePostBusinessAccountResponse) Set(val *PostBusinessAccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePostBusinessAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePostBusinessAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostBusinessAccountResponse(val *PostBusinessAccountResponse) *NullablePostBusinessAccountResponse {
	return &NullablePostBusinessAccountResponse{value: val, isSet: true}
}

func (v NullablePostBusinessAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostBusinessAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
