/*
StampWallet API Server

Testing ItemDefinitionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_ItemDefinitionsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ItemDefinitionsApiService AddItemDefinition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ItemDefinitionsApi.AddItemDefinition(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemDefinitionsApiService DeleteItemDefinition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var definitionId string

		resp, httpRes, err := apiClient.ItemDefinitionsApi.DeleteItemDefinition(context.Background(), definitionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemDefinitionsApiService GetItemDefinitions", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ItemDefinitionsApi.GetItemDefinitions(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemDefinitionsApiService UpdateItemDefinition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var definitionId string

		resp, httpRes, err := apiClient.ItemDefinitionsApi.UpdateItemDefinition(context.Background(), definitionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
