/*
StampWallet API Server

Testing TransactionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_TransactionApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TransactionApiService GetTransactionStatus", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var businessId string
		var transactionCode string

		resp, httpRes, err := apiClient.TransactionApi.GetTransactionStatus(context.Background(), businessId, transactionCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionApiService StartTransaction", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var businessId string

		resp, httpRes, err := apiClient.TransactionApi.StartTransaction(context.Background(), businessId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
