/*
StampWallet API Server

Testing FileApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_FileApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FileApiService DeleteFile", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string

		resp, httpRes, err := apiClient.FileApi.DeleteFile(context.Background(), fileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FileApiService GetFile", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string

		resp, httpRes, err := apiClient.FileApi.GetFile(context.Background(), fileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FileApiService UploadFile", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var fileId string

		resp, httpRes, err := apiClient.FileApi.UploadFile(context.Background(), fileId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
