services:
  backend:
    environment:
      #GIN_MODE: release
      STAMPWALLET_EMAILVERIFICATIONFRONTENDURL: 
      STAMPWALLET_SMTPCONFIG_SERVERHOSTNAME: smtp.gmail.com
      STAMPWALLET_SMTPCONFIG_SERVERPORT: 465
      STAMPWALLET_SMTPCONFIG_USERNAME: 
      STAMPWALLET_SMTPCONFIG_PASSWORD: 
      STAMPWALLET_SMTPCONFIG_SENDEREMAIL: 
