/*
 * StampWallet API Server
 *
 * StampWallet API Server REST Specification
 *
 * API version: 0.1.0
 * Contact: fbstachura@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type GetBusinessAccountResponseAllOf struct {

	Nip string `json:"nip,omitempty"`

	Krs string `json:"krs,omitempty"`

	Regon string `json:"regon,omitempty"`

	OwnerName string `json:"ownerName,omitempty"`
}
