/*
 * StampWallet API Server
 *
 * StampWallet API Server REST Specification
 *
 * API version: 0.1.0
 * Contact: fbstachura@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type ItemActionTypeEnum string

// List of ItemActionTypeEnum
const (
	NO_ACTION ItemActionTypeEnum = "NO_ACTION"
	REDEEMED  ItemActionTypeEnum = "REDEEMED"
	RECALLED  ItemActionTypeEnum = "RECALLED"
	CANCELLED ItemActionTypeEnum = "CANCELLED"
)
