/*
 * StampWallet API Server
 *
 * StampWallet API Server REST Specification
 *
 * API version: 0.1.0
 * Contact: fbstachura@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type LocalCardApiModel struct {

	PublicId string `json:"publicId,omitempty"`

	Name string `json:"name,omitempty"`

	Type string `json:"type,omitempty"`

	Code string `json:"code,omitempty"`
}
