/*
 * StampWallet API Server
 *
 * StampWallet API Server REST Specification
 *
 * API version: 0.1.0
 * Contact: fbstachura@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type TransactionStateEnum string

// List of TransactionStateEnum
const (
	STARTED    TransactionStateEnum = "STARTED"
	PROCESSING TransactionStateEnum = "PROCESSING"
	FINISHED   TransactionStateEnum = "FINISHED"
	EXPIRED    TransactionStateEnum = "EXPIRED"
)
