/*
 * StampWallet API Server
 *
 * StampWallet API Server REST Specification
 *
 * API version: 0.1.0
 * Contact: fbstachura@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type GetUserVirtualCardResponse struct {
	Points int32 `json:"points,omitempty"`

	OwnedItems []OwnedItemApiModel `json:"ownedItems,omitempty"`

	BusinessDetails PublicBusinessDetailsApiModel `json:"businessDetails,omitempty"`
}
