/*
 * StampWallet API Server
 *
 * StampWallet API Server REST Specification
 *
 * API version: 0.1.0
 * Contact: fbstachura@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type ItemActionApiModel struct {
	ItemId string `json:"itemId,omitempty"`

	Action ItemActionTypeEnum `json:"action,omitempty"`
}
