/*
 * StampWallet API Server
 *
 * lol
 *
 * API version: 0.1.0
 * Contact: fbstachura@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type PostAccountRequest struct {

	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`
}
