/*
 * StampWallet API Server
 *
 * StampWallet API Server REST Specification
 *
 * API version: 0.1.0
 * Contact: fbstachura@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type PostBusinessAccountRequest struct {

	Name string `json:"name,omitempty"`

	Address string `json:"address,omitempty"`

	GpsCoordinates string `json:"gpsCoordinates,omitempty"`

	Nip string `json:"nip,omitempty"`

	Krs string `json:"krs,omitempty"`

	Regon string `json:"regon,omitempty"`

	OwnerName string `json:"ownerName,omitempty"`
}
