/*
 * StampWallet API Server
 *
 * lol
 *
 * API version: 0.1.0
 * Contact: fbstachura@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type DefaultResponse struct {

	Status string `json:"status,omitempty"`

	Message string `json:"message,omitempty"`
}
