/*
 * StampWallet API Server
 *
 * StampWallet API Server REST Specification
 *
 * API version: 0.1.0
 * Contact: fbstachura@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type DefaultResponseStatusEnum string

// List of DefaultResponseStatusEnum
const (
	OK DefaultResponseStatusEnum = "OK"
	CREATED DefaultResponseStatusEnum = "CREATED"
	NOT_FOUND DefaultResponseStatusEnum = "NOT_FOUND"
	FORBIDDEN DefaultResponseStatusEnum = "FORBIDDEN"
	ALREADY_EXISTS DefaultResponseStatusEnum = "ALREADY_EXISTS"
	UNAUTHORIZED DefaultResponseStatusEnum = "UNAUTHORIZED"
	INVALID_REQUEST DefaultResponseStatusEnum = "INVALID_REQUEST"
	CONFLICT DefaultResponseStatusEnum = "CONFLICT"
)
